// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Lambdaapi
{
    [LambdaapiResourceType("awslambdaapi:index:CronLambda")]
    public partial class CronLambda : Pulumi.ComponentResource
    {
        /// <summary>
        /// Specifies the cron schedule.
        /// </summary>
        [Output("eventRule")]
        public Output<Pulumi.Aws.CloudWatch.EventRule> EventRule { get; private set; } = null!;

        /// <summary>
        /// The website URL.
        /// </summary>
        [Output("eventTarget")]
        public Output<Pulumi.Aws.CloudWatch.EventTarget> EventTarget { get; private set; } = null!;


        /// <summary>
        /// Create a CronLambda resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CronLambda(string name, CronLambdaArgs args, ComponentResourceOptions? options = null)
            : base("awslambdaapi:index:CronLambda", name, args ?? new CronLambdaArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class CronLambdaArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// Lambda function to execute as a cron job
        /// </summary>
        [Input("handlerArn", required: true)]
        public Input<string> HandlerArn { get; set; } = null!;

        /// <summary>
        /// Rate that the cron lambda will execute.
        /// </summary>
        [Input("rateInMinutes", required: true)]
        public Input<double> RateInMinutes { get; set; } = null!;

        public CronLambdaArgs()
        {
        }
    }
}
