# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities
import pulumi_aws

__all__ = ['LambdaApiArgs', 'LambdaApi']

@pulumi.input_type
class LambdaApiArgs:
    def __init__(__self__, *,
                 lambda_arn: pulumi.Input[str]):
        """
        The set of arguments for constructing a LambdaApi resource.
        :param pulumi.Input[str] lambda_arn: The arn of the lambda function
        """
        pulumi.set(__self__, "lambda_arn", lambda_arn)

    @property
    @pulumi.getter(name="lambdaArn")
    def lambda_arn(self) -> pulumi.Input[str]:
        """
        The arn of the lambda function
        """
        return pulumi.get(self, "lambda_arn")

    @lambda_arn.setter
    def lambda_arn(self, value: pulumi.Input[str]):
        pulumi.set(self, "lambda_arn", value)


class LambdaApi(pulumi.ComponentResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 lambda_arn: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a LambdaApi resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] lambda_arn: The arn of the lambda function
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: LambdaApiArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a LambdaApi resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param LambdaApiArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(LambdaApiArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 lambda_arn: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        if opts is None:
            opts = pulumi.ResourceOptions()
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.version is None:
            opts.version = _utilities.get_version()
        if opts.id is not None:
            raise ValueError('ComponentResource classes do not support opts.id')
        else:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = LambdaApiArgs.__new__(LambdaApiArgs)

            if lambda_arn is None and not opts.urn:
                raise TypeError("Missing required property 'lambda_arn'")
            __props__.__dict__["lambda_arn"] = lambda_arn
            __props__.__dict__["bucket"] = None
        super(LambdaApi, __self__).__init__(
            'awslambdaapi:index:LambdaApi',
            resource_name,
            __props__,
            opts,
            remote=True)

    @property
    @pulumi.getter
    def bucket(self) -> pulumi.Output['pulumi_aws.s3.Bucket']:
        """
        The bucket resource.
        """
        return pulumi.get(self, "bucket")

