// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class CloudfrontS3 extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'awslambdaapi:index:CloudfrontS3';

    /**
     * Returns true if the given object is an instance of CloudfrontS3.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CloudfrontS3 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CloudfrontS3.__pulumiType;
    }

    /**
     * Cloudfront URL
     */
    public /*out*/ readonly domainName!: pulumi.Output<string>;

    /**
     * Create a CloudfrontS3 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CloudfrontS3Args, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.bucketName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'bucketName'");
            }
            inputs["bucketName"] = args ? args.bucketName : undefined;
            inputs["domainName"] = undefined /*out*/;
        } else {
            inputs["domainName"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(CloudfrontS3.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a CloudfrontS3 resource.
 */
export interface CloudfrontS3Args {
    /**
     * Name to give the S3 bucket which this Component will create.
     */
    readonly bucketName: pulumi.Input<string>;
}
