// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

import * as aws from "@pulumi/aws";

export class CronLambda extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'awslambdaapi:index:CronLambda';

    /**
     * Returns true if the given object is an instance of CronLambda.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CronLambda {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CronLambda.__pulumiType;
    }

    /**
     * Specifies the cron schedule.
     */
    public /*out*/ readonly eventRule!: pulumi.Output<aws.cloudwatch.EventRule>;
    /**
     * The website URL.
     */
    public /*out*/ readonly eventTarget!: pulumi.Output<aws.cloudwatch.EventTarget>;

    /**
     * Create a CronLambda resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CronLambdaArgs, opts?: pulumi.ComponentResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.handlerArn === undefined) && !opts.urn) {
                throw new Error("Missing required property 'handlerArn'");
            }
            if ((!args || args.rateInMinutes === undefined) && !opts.urn) {
                throw new Error("Missing required property 'rateInMinutes'");
            }
            inputs["handlerArn"] = args ? args.handlerArn : undefined;
            inputs["rateInMinutes"] = args ? args.rateInMinutes : undefined;
            inputs["eventRule"] = undefined /*out*/;
            inputs["eventTarget"] = undefined /*out*/;
        } else {
            inputs["eventRule"] = undefined /*out*/;
            inputs["eventTarget"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(CronLambda.__pulumiType, name, inputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a CronLambda resource.
 */
export interface CronLambdaArgs {
    /**
     * Lambda function to execute as a cron job
     */
    readonly handlerArn: pulumi.Input<string>;
    /**
     * Rate that the cron lambda will execute.
     */
    readonly rateInMinutes: pulumi.Input<number>;
}
